In [2]:
import pandas as pd

In [3]:
# Read a sample of the data
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow'
url = f"{prefix}/yellow_tripdata_2021-01.csv.gz"
url

'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2021-01.csv.gz'

In [4]:
# Load and display the first of data
df = pd.read_csv(url)
df.head()

/tmp/ipykernel_35524/346600521.py:2: DtypeWarning: Columns (0: store_and_fwd_flag) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1.0,2021-01-01 00:30:10,2021-01-01 00:36:12,1.0,2.10,1.0,N,142,43,2.0,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1.0,2021-01-01 00:51:20,2021-01-01 00:52:19,1.0,0.20,1.0,N,238,151,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1.0,2021-01-01 00:43:30,2021-01-01 01:11:06,1.0,14.70,1.0,N,132,165,1.0,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1.0,2021-01-01 00:15:48,2021-01-01 00:31:01,0.0,10.60,1.0,N,138,132,1.0,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2.0,2021-01-01 00:31:49,2021-01-01 00:48:21,1.0,4.94,1.0,N,68,33,1.0,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [5]:
# Checking the VendorID value
df.VendorID

0          1.0
1          1.0
2          1.0
3          1.0
4          2.0
          ...
1369760    NaN
1369761    NaN
1369762    NaN
1369763    NaN
1369764    NaN
Name: VendorID, Length: 1369765, dtype: float64

In [6]:
# Checking the value of 'tpep_pickup_datetime'
df['tpep_pickup_datetime']

0          2021-01-01 00:30:10
1          2021-01-01 00:51:20
2          2021-01-01 00:43:30
3          2021-01-01 00:15:48
4          2021-01-01 00:31:49
                  ...
1369760    2021-01-25 08:32:04
1369761    2021-01-25 08:34:00
1369762    2021-01-25 08:37:00
1369763    2021-01-25 08:28:00
1369764    2021-01-25 08:38:00
Name: tpep_pickup_datetime, Length: 1369765, dtype: str

In [7]:
# Checking the content of dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1369765 entries, 0 to 1369764
Data columns (total 18 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   VendorID               1271413 non-null  float64
 1   tpep_pickup_datetime   1369765 non-null  str
 2   tpep_dropoff_datetime  1369765 non-null  str
 3   passenger_count        1271413 non-null  float64
 4   trip_distance          1369765 non-null  float64
 5   RatecodeID             1271413 non-null  float64
 6   store_and_fwd_flag     1271413 non-null  str
 7   PULocationID           1369765 non-null  int64
 8   DOLocationID           1369765 non-null  int64
 9   payment_type           1271413 non-null  float64
 10  fare_amount            1369765 non-null  float64
 11  extra                  1369765 non-null  float64
 12  mta_tax                1369765 non-null  float64
 13  tip_amount             1369765 non-null  float64
 14  tolls_amount           1369765 non-null  float64
 15  improvement_surcharge  1369765 non-null  float64
 16  total_amount           1369765 non-null  float64
 17  congestion_surcharge   1369765 non-null  float64
dtypes: float64(13), int64(2), str(3)
memory usage: 239.1 MB

In [41]:
# Assign the dtype
dtype = {
    'VendorID':'Int64', 
    'passenger_count':'Int64', 
    'trip_distance':'float64', 
    'RatecodeID':'Int64', 
    'store_and_fwd_flag':'string',
    'PULocationID':'Int64', 
    'DOLocationID':'Int64', 
    'payment_type':'Int64', 
    'fare_amount':'float64', 
    'extra':'float64',
    'mta_tax':'float64', 
    'tip_amount':'float64', 
    'tolls_amount':'float64', 
    'improvement_surcharge':'float64',
    'total_amount':'float64', 
    'congestion_surcharge':'float64'
}

# Parsing date features
parse_dates = [
    'tpep_pickup_datetime', 
    'tpep_dropoff_datetime'
]

# loading the dataset, with assigning dtype and pasing the date
df = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates
)

In [9]:
# Checking length of the data
len(df)

1369765

In [10]:
# Load the data
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.00,3.00,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.00,0.50,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.00,0.50,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.00,0.50,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.50,0.50,0.5,4.06,0.0,0.3,24.36,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1369760,<NA>,2021-01-25 08:32:04,2021-01-25 08:49:32,<NA>,8.80,<NA>,<NA>,135,82,<NA>,21.84,2.75,0.5,0.00,0.0,0.3,25.39,0.0
1369761,<NA>,2021-01-25 08:34:00,2021-01-25 09:04:00,<NA>,5.86,<NA>,<NA>,42,161,<NA>,26.67,2.75,0.5,0.00,0.0,0.3,30.22,0.0
1369762,<NA>,2021-01-25 08:37:00,2021-01-25 08:53:00,<NA>,4.45,<NA>,<NA>,14,106,<NA>,25.29,2.75,0.5,0.00,0.0,0.3,28.84,0.0
1369763,<NA>,2021-01-25 08:28:00,2021-01-25 08:50:00,<NA>,10.04,<NA>,<NA>,175,216,<NA>,28.24,2.75,0.5,0.00,0.0,0.3,31.79,0.0
1369764,<NA>,2021-01-25 08:38:00,2021-01-25 08:50:00,<NA>,4.93,<NA>,<NA>,248,168,<NA>,20.76,2.75,0.5,0.00,0.0,0.3,24.31,0.0

In [11]:
# Checking the content of the data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1369765 entries, 0 to 1369764
Data columns (total 18 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   VendorID               1271413 non-null  Int64
 1   tpep_pickup_datetime   1369765 non-null  datetime64[us]
 2   tpep_dropoff_datetime  1369765 non-null  datetime64[us]
 3   passenger_count        1271413 non-null  Int64
 4   trip_distance          1369765 non-null  float64
 5   RatecodeID             1271413 non-null  Int64
 6   store_and_fwd_flag     1271413 non-null  string
 7   PULocationID           1369765 non-null  Int64
 8   DOLocationID           1369765 non-null  Int64
 9   payment_type           1271413 non-null  Int64
 10  fare_amount            1369765 non-null  float64
 11  extra                  1369765 non-null  float64
 12  mta_tax                1369765 non-null  float64
 13  tip_amount             1369765 non-null  float64
 14  tolls_amount           1369765 non-null  float64
 15  improvement_surcharge  1369765 non-null  float64
 16  total_amount           1369765 non-null  float64
 17  congestion_surcharge   1369765 non-null  float64
dtypes: Int64(6), datetime64[us](2), float64(9), string(1)
memory usage: 197.2 MB

In [12]:
# Install sqlalchemy, psycopg2 to digest data into postgresql
!uv add sqlalchemy psycopg2-binary

Resolved 119 packages in 1ms
Audited 10 packages in 0.28ms

In [13]:
# Create engine
from sqlalchemy import create_engine
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [42]:
# Run create table to save in postgresql
df.head(0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')

0

In [43]:
# Load the dataset into chunks
df_iter = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    chunksize=100000
)

In [23]:
# Install tqdm
!uv add tqdm

Resolved 120 packages in 878ms
Prepared 1 package in 23ms
░░░░░░░░░░░░░░░░░░░░ [0/1] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 1 package in 5ms
 + tqdm==4.67.2

In [44]:
from tqdm.auto import tqdm

# Load chunk data into postgresql
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')

0it [00:00, ?it/s]